//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace De_01
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Sinhvien
    {
        public string MaSV { get; set; }
        public string HotenSV { get; set; }
        public string MaLop { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        [Browsable(false)]    
        
        public virtual Lop Lop { get; set; }
    }
}
